site_name: Python base
site_description: курс по основам языка Python для вузов

docs_dir: docs/
theme:
  name: material
  icon:
    logo: material/language-python
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  hide:
    - navigation
    - toc
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: light blue

nav:
  - Информация о курсе:
  - Раздел 1. Основы языка Python:
    - Что такое Python? Начало работы: 00_intro.md
    - Типы данных. Целые числа и числа с плавающей точкой: 01_int_and_float.md
    - Переменные. Строки: 02_vars_and_str.md
    - Задача №1. Вывод песен из строки: 03_first_task.md
    - Коллекции. Списки и кортежи: 04_list_and_tuples.md
    - Задача №2. Изменение списка покупок. Форматированный вывод: 05_second_task.md
    - Условный оператор if. Операторы цикла while и for: 06_if_while_for.md
    - Задача №3. Словари и их свойства. Списковое включение: 07_third_task.md
    - Функции. Свойства и параметры функций: 08_functions.md
    - Шпаргалка по разделу 1: 09_cheatsheet.md
  - Раздел 2. Импорт. Работа с файлами:
    - Импорт: 01_module_and_package.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pyshkovni
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCFl8u5LGFv0UqhfP5whEoVA
    - icon: fontawesome/brands/telegram
      link: https://t.me/pyshkovni
    - icon: fontawesome/brands/vk
      link: https://vk.com/pyshkovni

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/pyshkovni"  target="_blank" rel="noopener">Nikita Pyshkov</a>